### ISSUE TITLE
Example for usage with ttypescript

### ISSUE THREAD

**Issue by aminya** [sapphi-red/ts-transformer-for-of#2]
Could you add an example for usage with https://github.com/cevek/ttypescript/?

**Comment by sapphi-red** [comment]
https://github.com/sapphi-red/ts-transformer-for-of#how-to-use-the-custom-transformer
> See [kimamula/ts-transformer-keys](https://github.com/kimamula/ts-transformer-keys/blob/master/README.md#how-to-use-the-custom-transformer).

[kimamula/ts-transformer-keys:/README.md#About ttypescript](https://github.com/kimamula/ts-transformer-keys/blob/master/README.md#ttypescript)

This transformer is possible to use as same as above.
